### ISSUE TITLE
Can't Get This To Work

### ISSUE THREAD

**Issue by theskyfloor** [chadcrowell/newsletter-subscribe-checkbox-craftcms#2]
Can't seem to get this to work. Are there any requirements for Sprout Forms version? 

Does the email field have to also have a specific handle? 

Is part of the problem that the field name/id renders out as `newsletterSubscribeCheckbox` even though we are naming the field `newsletterSubscribe`?

I can give more info if needed. Sorry to bother just hoping to be able to get this work. Thanks for putting it together!

**Comment by chadcrowell** [comment]
Hi there - yes, the field does have to have a specific handle. In the readme instructions #6:

Input the field name and handle exactly like this:
Name: Newsletter Subscribe
Handle: newsletterSubscribe

Give that a try.

**Comment by theskyfloor** [comment]
I tried it that way and it still didn't work. I was asking about the field name because I could see references to both `newsletterSubscribeCheckbox` and `newsletterSubscribe` in the plug-in code... wasn't sure if it was an unintentional discrepancy or if that was how it was supposed to be coded.

![screen shot 2016-08-19 at 10 41 15 am](https://cloud.githubusercontent.com/assets/8887839/17815352/92e52e4e-65f9-11e6-96c7-8e129c8a883a.png)

**Comment by chadcrowell** [comment]
It was intentional at the time - i don't recall offhand why I did it that way (first plugin). I know it worked on our site and at least one other person who downloaded it and installed from here. I see why you question that and you can certainly try changing it to see if it works. I won't have time today to look into it unfortunately.

**Comment by theskyfloor** [comment]
No worries! I am swamped as well on another project but I will see if I can troubleshoot more next week! Thanks for the help : )

**Comment by theskyfloor** [comment]
Still haven't gotten it working but did figure out one of my issues... your service file calls for `require_once CRAFT_PLUGINS_PATH . 'newslettersubscribecheckbox/vendor/mcapi_v3/MailChimp.php';` but in the repo the file is `Mailchimp.php` notice the lowercase `c` - my server is case sensitive so it wasnt even loading that file.

![screen shot 2016-08-22 at 10 16 28 pm](https://cloud.githubusercontent.com/assets/8887839/17879270/2e07b518-68b6-11e6-92e7-c1a7acb7b514.png)

**Comment by theskyfloor** [comment]
Actually it appears to be working! So that was the issue.

**Comment by theskyfloor** [comment]
It would be cool if this plug-in also recorded the value in the Craft database (checkbox checked or not)... I wonder if Ben could help with that?

**Comment by chadcrowell** [comment]
That’s good news. You know, I fixed that casing issue, but I’m thinking now
that I never uploaded it to SUC. I’ll do that now… sorry for the trouble I
should have taken care of that.

I was working on this the other day and noticed it wasn’t saving to the db,
so I’m going to work on that soon as well.
